# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yt_down.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import *
from pytube import YouTube


class Ui_Dialog(object):
    def __init__(self):
        self.lbl_welcome = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Youtube Downloader")
        Dialog.resize(800, 800)
        Dialog.setStyleSheet("background-color: rgb(255, 247, 243);")
        self.lbl_welcome = QtWidgets.QLabel(Dialog)
        self.lbl_welcome.setGeometry(QtCore.QRect(80, 40, 450, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_welcome.setFont(font)
        self.lbl_welcome.setMouseTracking(False)
        self.lbl_welcome.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_welcome.setAutoFillBackground(False)
        self.lbl_welcome.setStyleSheet("font: 24pt \"Calibri\";")
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 100, 180, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 14pt \"Calibri\";")
        self.label.setObjectName("label")
        self.ent_link = QtWidgets.QLineEdit(Dialog)
        self.ent_link.setGeometry(QtCore.QRect(25, 150, 450, 31))
        self.ent_link.setStyleSheet("font: 12pt \"Calibri\";\n"
                                    "color: rgb(0, 0, 0);")
        self.ent_link.setObjectName("ent_link")
        self.btn_link = QtWidgets.QPushButton(Dialog)
        self.btn_link.setGeometry(QtCore.QRect(500, 150, 75, 31))
        self.btn_link.setStyleSheet("font: 12pt \"Calibri\";\n"
                                    "color: rgb(0, 0, 0);")
        self.btn_link.setObjectName("btn_link")
        self.btn_link.clicked.connect(self.button_function)
        self.checkBox_audio = QtWidgets.QCheckBox(Dialog)
        self.checkBox_audio.setGeometry(QtCore.QRect(260, 100, 80, 17))
        self.checkBox_audio.setStyleSheet("font: 14pt \"Calibri\";")
        self.checkBox_audio.setObjectName("checkBox_audio")
        #        self.checkBox_audio.clicked.connect(self.checkBox_function)
        self.checkBox_video = QtWidgets.QCheckBox(Dialog)
        self.checkBox_video.setGeometry(QtCore.QRect(360, 100, 80, 17))
        self.checkBox_video.setStyleSheet("font: 14pt \"Calibri\";")
        self.checkBox_video.setObjectName("checkBox_video")
        #        self.checkBox_video.clicked.connect(self.checkBox_function)
        self.lbl_desc = QtWidgets.QLabel(Dialog)
        self.lbl_desc.setGeometry(QtCore.QRect(50, 250, 700, 50))
        self.lbl_desc.setObjectName("lbl_desc")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(50, 360, 700, 235))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_welcome.setText(_translate("Dialog", "WELCOME DOWNLOADERS"))
        self.label.setText(_translate("Dialog", "Select Audio/Video"))
        self.btn_link.setText(_translate("Dialog", "Links"))
        self.checkBox_audio.setText(_translate("Dialog", "Audio"))
        self.checkBox_video.setText(_translate("Dialog", "Video"))
        self.lbl_desc.setText(_translate("Dialog", ""))

    # This is link button function

    def button_function(self):
        self.listWidget.clear()
        yt = YouTube(self.ent_link.text())
        self.lbl_desc.setText(description(yt))
        streams_list = []
        if self.checkBox_audio.isChecked():
            streams_list.extend(fetch_audio_streams(yt))
        if self.checkBox_video.isChecked():
            streams_list.extend(fetch_video_streams(yt))
        for item in streams_list:
            self.listWidget.addItem(str(item))

    # def checkBox_function(self):
    #     print(self.checkBox_audio.isChecked())
    #     print(self.checkBox_video.isChecked())


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
